### ISSUE TITLE
Corrections messages fr (fr.po)

### ISSUE THREAD

**Issue by Fourchaux** [Octachron/babilim#1]
Le fichier "fr.po"

Note1: Un peu d'histoire : 20 ans en arrière. Caml Light.

https://caml.inria.fr/pub/old_caml_site/FAQ/FAQ_DEBUTANT-fra.html#messages
Des messages, en 5 langues. C'était Babel !  

Et voilà le fichier des différentes traductions (P. Weis & X.L.) :
https://github.com/camllight/camllight/blob/master/sources/src/camlmsgs.txt

On est allègrement passé de 80 messages à 530+ aujourd'hui. Ouch...
Dommage qu'aucune adaptation/màj n'ait été faite pour OCaml.

Note2: Pourquoi parles-tu de "_bad French translation_" ou de "_full (but atrocious) french translation_" ?
atrocious: adj. Exceptionally bad; abominable.
Cette traduction n'a absolument RIEN d'atrocious. 

Se farcir l'écriture d'un 1/2 millier de messages d'erreur doit déjà être une purge en soi. 
Si en plus il y a de l'autoflagellation... (je subodore un petit côté maso, non ?)

Note finale:
Un PR corrigeant quelques coquilles/expressions présentes dans les messages fr est-il intéressant ?

Ou bien faut-il attendre un peu (sachant qu "_unfortunately, at this point, I cannot guaranteed that this work will not be in vain._") ?

(On peut quand même espérer que ce type de proposition soit acceptée. N'est-il pas ?
Et que quelques non-indo-européens contribuent.)

**Comment by Octachron** [comment]
> Note2: Pourquoi parles-tu de "bad French translation" ou de "full (but atrocious) french translation" ?

Le but principal de la traduction actuelle était de vérifier que les messages exposés aux traducteurs sont bel et bien traduisibles; par exemple pour la traduction française cela requiert d'avoir suffisamment d'information pour les accords de genres et de nombres. J'espère que la granularité des messages est suffisante pour des langues bien plus éloignées de l'anglais que le français (turque, basque, finnois, polonais, japonais ?) sans trop de contorsions, mais c'est difficile à savoir. 

La qualité de la traduction n'était pas un objectif premier de cette traduction, en particulier la traduction actuelle manque de cohérence interne sur la traduction de certains termes (`unbound/bound` et `to match` me viennent à l'esprit). Si la traduction n'est pas atroce, c'est un accident heureux mais un accident néanmoins; et la traduction aurait bien besoin de quelques passes de relectures.

> Un PR corrigeant quelques coquilles/expressions présentes dans les messages fr est-il intéressant ?

Je n'aurais rien contre, bien au contraire.

> Ou bien faut-il attendre un peu (sachant qu "unfortunately, at this point, I cannot guaranteed that this work will not be in vain.") ?

Pour équilibrer mon propos, avoir des contributeurs pour les traductions, cela peut aussi aider à valider l'intérêt de l'internationalisation dans le compilateur.

> On peut quand même espérer que ce type de proposition soit acceptée. N'est-il pas ?

On peut l'espérer, en tout cas la proposition a été optimisée dans ce sens, mais rien n'est encore certain.

**Comment by Fourchaux** [comment]
Quelques corrections. 
Voir: https://github.com/Octachron/babilim/pull/2
